# API Integration Framework Configuration
api:
  framework:
    # Connection settings
    connection-timeout-ms: 5000
    read-timeout-ms: 30000
    max-connections: 100
    max-connections-per-route: 20
    
    # Retry settings
    max-retry-attempts: 3
    retry-delay-ms: 1000
    
    # Logging settings
    enable-logging: true
    
    # Mocking settings (for testing/development)
    enable-mocking: false
    mock-server-url: http://localhost:8089

# Spring Boot Configuration
spring:
  application:
    name: api-integration-framework
  
# Logging Configuration
logging:
  level:
    com.company.apiframework: DEBUG
    org.springframework.web.client: DEBUG
    org.apache.http: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints (for monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized 